Repository devblogs-ir/PipelineDesignPattern, pull requests merged in 2023-12, with the labels that each got.

#3 Created Pipeline
  src/Niloo Mont/PipelineDesignPattern/BannedIPException.cs
  src/Niloo Mont/PipelineDesignPattern/Framework.cs
  src/Niloo Mont/PipelineDesignPattern/HttpContext.cs
  src/Niloo Mont/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/Niloo Mont/PipelineDesignPattern/PipelineDesignPattern.sln
  src/Niloo Mont/PipelineDesignPattern/ProductController.cs
  src/Niloo Mont/PipelineDesignPattern/Program.cs
  src/Niloo Mont/README.md
Labels: **ready to review**

#8 Add Simple pipeline design pattern project
  src/hamidreza rahmani/PipelineDesignPattern/CountryBlockedException .cs
  src/hamidreza rahmani/PipelineDesignPattern/CountryController.cs
  src/hamidreza rahmani/PipelineDesignPattern/Framework.cs
  src/hamidreza rahmani/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/hamidreza rahmani/PipelineDesignPattern/Program.cs
Labels: **ready to review**

#14 Simple pipeline design pattern
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern.sln
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/Framework.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/HttpContext.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/IpNotAllowedException.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/ProductController.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/Program.cs
  src/ArezooKamane/README.md
Labels: **ready to review**

#15 Feat/niloufar mont
  src/Niloo Mont/PipelineDesignPattern/BannedIPException.cs
  src/Niloo Mont/PipelineDesignPattern/Framework.cs
  src/Niloo Mont/PipelineDesignPattern/HttpContext.cs
  src/Niloo Mont/PipelineDesignPattern/ProductController.cs
Labels: **ready to review**

#4 Feat/abolfazl kabiri
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/.editorconfig
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Common/Common.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Controllers/ProductController.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/CustomExceptions/InaccessibilityException.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/CustomExceptions/InvalidIpAddressException.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/CustomExceptions/UnknownIpAddressException.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/AuthenticationStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/CorsStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/ExceptionHandlingStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/RouteStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/IPipelineContext.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/IPipelineStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/Pipeline.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/PipelineContext.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/PipelineDesignPattern.SimpleImplement.csproj
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Program.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.sln
  src/Abolfazl Kabiri/README.md
Labels: **ready to review**

#21 Adding Mohammad Zarei pipline
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern.sln
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Controllers/ProductsController.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Exceptions/BlockedIpException.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Framework.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/MyContext.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/PiplineDesignPattern.csproj
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Program.cs
Labels: **ready to review**

#1 add pipline design pattern project
  src/MojtabaValizadeh/PipelineDesignPattern/CountryBlockedException.cs
  src/MojtabaValizadeh/PipelineDesignPattern/CountryController.cs
  src/MojtabaValizadeh/PipelineDesignPattern/Framework.cs
  src/MojtabaValizadeh/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/MojtabaValizadeh/PipelineDesignPattern/Program.cs
Labels: **ready to review**

#5 feat: add custome pipeline
  src/reza pourabbasi/PipelineDesignPattern/Framework.cs
  src/reza pourabbasi/PipelineDesignPattern/HttpContext.cs
  src/reza pourabbasi/PipelineDesignPattern/IPNotProvideException.cs
  src/reza pourabbasi/PipelineDesignPattern/InvalidIPException.cs
  src/reza pourabbasi/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/reza pourabbasi/PipelineDesignPattern/PipelineDesignPattern.sln
  src/reza pourabbasi/PipelineDesignPattern/ProductsCintroller.cs
  src/reza pourabbasi/PipelineDesignPattern/Program.cs
Labels: **ready to review**

#7 function chaining practice done
  src/MohammadJebelli/PipelineDesignPattern.sln
  src/MohammadJebelli/PipelineDesignPattern/.editorconfig
  src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
  src/MohammadJebelli/PipelineDesignPattern/HttpContext.cs
  src/MohammadJebelli/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/MohammadJebelli/PipelineDesignPattern/ProductController.cs
  src/MohammadJebelli/PipelineDesignPattern/Program.cs
Labels: **ready to review**, ** need some changes **

#22 PipelineDesignPattern Project
  src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
  src/Amin Afrasiabi/PipelineDesignPattern/HttpContext.cs
  src/Amin Afrasiabi/PipelineDesignPattern/IranianIPBlockedException.cs
  src/Amin Afrasiabi/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/Amin Afrasiabi/PipelineDesignPattern/PipelineDesignPattern.sln
  src/Amin Afrasiabi/PipelineDesignPattern/ProductsController.cs
  src/Amin Afrasiabi/PipelineDesignPattern/Program.cs
  src/Amin Afrasiabi/README.md
Labels: **ready to review**

#23 Feat/sara gholampour
  src/Design.Cohesion/Design.Cohesion/Temporal.cs
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/.gitignore
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/indexLayout.xml
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/inspectionProfiles/Project_Default.xml
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/jsLibraryMappings.xml
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/misc.xml
  src/Niloo Mont/PipelineDesignPattern/.idea/.idea.PipelineDesignPattern/.idea/vcs.xml
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/.gitignore
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/.name
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/encodings.xml
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/indexLayout.xml
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/inspectionProfiles/Project_Default.xml
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/jsLibraryMappings.xml
  src/SaraGholampour/.idea/.idea.OmletSln/.idea/vcs.xml
  src/SaraGholampour/OmletPipeline/DuplicateStageException.cs
  src/SaraGholampour/OmletPipeline/IncorrectStageException.cs
  src/SaraGholampour/OmletPipeline/InvalidStageException.cs
  src/SaraGholampour/OmletPipeline/OmletContext.cs
  src/SaraGholampour/OmletPipeline/OmletController.cs
  src/SaraGholampour/OmletPipeline/OmletPipeline.csproj
  src/SaraGholampour/OmletPipeline/Program.cs
  src/SaraGholampour/OmletSln.sln
Labels: **ready to review**

#18 create pipeline Project
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/CheckBanndIPAddress.cs
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/Framework.cs
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/HttpContext.cs
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/PipelineProject.ClassLib.csproj
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/ProductController.cs
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.ClassLib/Program.cs
  src/ArvinMashayekhi/PipelineDesignPattern/PipelineProject.sln
Labels: **ready to review**, ** need some changes **

#9 Feat/mahdi salahinia
  src/Mahdi Salahinia/MyPipelinePattern.sln
  src/Mahdi Salahinia/PipelineDesignPatternExp/CountryIp.cs
  src/Mahdi Salahinia/PipelineDesignPatternExp/CustomException.cs
  src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
  src/Mahdi Salahinia/PipelineDesignPatternExp/HttpContext.cs
  src/Mahdi Salahinia/PipelineDesignPatternExp/IpController.cs
  src/Mahdi Salahinia/PipelineDesignPatternExp/PipelineDesignPatternExp.csproj
  src/Mahdi Salahinia/PipelineDesignPatternExp/Program.cs
Labels: **ready to review**

#25 Issues solved
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Context.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Controllers/ProductController.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Exceptions/BlockedIpException.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Framework.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Program.cs
Labels: **ready to review**

#26 Feat/abolfazl kabiri
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Common/ExtentionMethods.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Common/Ip.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Common/Url.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/CustomExceptions/InvalidRequestException.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/CustomExceptions/NotImplementedPipelineException.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/AuthenticationPipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/AuthenticationStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/CorsPipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/EndPointPipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/ExceptionHandlingPipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/ExceptionHandlingStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/RoutePipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Patterns/HttpRequestPattern.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/IPipe.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/IPipelineContext.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/IPipelineStep.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/Pipeline.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/PipelineContext.cs
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/PipelineDesignPattern.SimpleImplement.csproj
  src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Program.cs
Labels: **ready to review**

#29 pipeline practice
  src/MohammadJebelli/PipelineDesignPattern.sln
  src/MohammadJebelli/PipelineDesignPattern/AuthenticaionPipe.cs
  src/MohammadJebelli/PipelineDesignPattern/EndPointPipe.cs
  src/MohammadJebelli/PipelineDesignPattern/ExceptionHandlerPipe.cs
  src/MohammadJebelli/PipelineDesignPattern/HttpContext.cs
  src/MohammadJebelli/PipelineDesignPattern/Pipe.cs
  src/MohammadJebelli/PipelineDesignPattern/PipeBuilder.cs
  src/MohammadJebelli/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/MohammadJebelli/PipelineDesignPattern/ProductController.cs
  src/MohammadJebelli/PipelineDesignPattern/Program.cs
Labels: ** need some changes **

#32 Builder for PipelineDesignPattern
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/AuthenticationPipe.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/BasePipe.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/EndPointPipe.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/ExceptionHandlingPipe.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/Framework.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/HttpContext.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/IPRange.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/IpNotAllowedException.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/IpRangeChecker.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/PipelineBuilder.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/ProductController.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/ProductsController.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/Program.cs
  src/ArezooKamane/PipelineDesignPattern/PipelineDesignPattern/ir.csv
Labels: **ready to review**

#34 Pipline Builder added!
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Context.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Controllers/OrdersController.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Controllers/ProductController.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Controllers/UsersController.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Exceptions/BlockedIpException.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Framework.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/PipelineBuilder.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Pipes/AuthenticationHandlingPipe.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Pipes/EndpointPipe.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Pipes/ExceptionHandlingPipe.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Pipes/Pipe.cs
  src/Mohammad Zarei/PiplineDesignPattern/PiplineDesignPattern/Program.cs
Labels: **ready to review**

#33 Feat/zahra liaghatmand
  src/ZahraLiaghatmand/PipelineDesignPattern/Controllers/OrdersController.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Controllers/ProductsController.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Exceptions/IPBanException.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Framework.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/HttpContext.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/ZahraLiaghatmand/PipelineDesignPattern/PipelineDesignPattern.sln
  src/ZahraLiaghatmand/PipelineDesignPattern/Pipes/AuthenticationPipe.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Pipes/EndpointPipe.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Pipes/ExceptionHandlingPipe.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Pipes/Pipe.cs
  src/ZahraLiaghatmand/PipelineDesignPattern/Program.cs
Labels: **ready to review**

#38 Create pipeline
  src/SomayehMehri/PipelineDesignPattern.sln
  src/SomayehMehri/PipelineDesignPattern/Framework.cs
  src/SomayehMehri/PipelineDesignPattern/HttpContext.cs
  src/SomayehMehri/PipelineDesignPattern/PipelineDesignPattern.csproj
  src/SomayehMehri/PipelineDesignPattern/ProductController.cs
  src/SomayehMehri/PipelineDesignPattern/Program.cs
Labels: **ready to review**

#27 Feat/niloufar mont
  src/Niloo Mont/PipelineCLITool/AuthenticationPipe.cs
  src/Niloo Mont/PipelineCLITool/BasePipe.cs
  src/Niloo Mont/PipelineCLITool/EndPointPipe.cs
  src/Niloo Mont/PipelineCLITool/ExceptionHandlingPipe.cs
  src/Niloo Mont/PipelineCLITool/Exceptions.cs
  src/Niloo Mont/PipelineCLITool/Framework.cs
  src/Niloo Mont/PipelineCLITool/GlobalUsings.cs
  src/Niloo Mont/PipelineCLITool/HttpContext.cs
  src/Niloo Mont/PipelineCLITool/PipelineBuilder.cs
  src/Niloo Mont/PipelineCLITool/PipelineCLITool.csproj
  src/Niloo Mont/PipelineCLITool/PipelineCLITool.sln
  src/Niloo Mont/PipelineCLITool/ProductsController.cs
  src/Niloo Mont/PipelineCLITool/Program.cs
  src/Niloo Mont/PipelineCLITool/User.cs
  src/Niloo Mont/README.md
Labels: **ready to review**

#42 Added pipeline 1
  src/Maryam Eftekhari/Pipeline/Pipeline.sln
  src/Maryam Eftekhari/Pipeline/Pipline/Constants.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Context/HttpContext.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Exceptions/DeniedIPException.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Framework.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Models/IpInfo.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Pipeline.csproj
  src/Maryam Eftekhari/Pipeline/Pipline/ProductsController.cs
  src/Maryam Eftekhari/Pipeline/Pipline/Program.cs
Labels: **ready to review**
